group: travis_latest
language: python
cache: pip
jobs:
    include:
      # We put 3.6 first since this is where flake8 and docs are testted
      - python: 3.6
      # We put pypy towards the beginning because for some reason the build takes much longer
      - python: pypy
      - python: pypy3
      - python: 2.7
      - python: 3.4
      - python: 3.5
      - python: 3.7
        dist: xenial
        sudo: true
      - python: 3.8-dev
        dist: xenial
        sudo: true
      - python: nightly
        dist: xenial
        sudo: true
matrix:
    allow_failures:
        - python: 3.7
        - python: 3.8-dev
        - python: nightly

install:
  - travis_retry pip install --upgrade pip
  - travis_retry pip install --upgrade tox tox-travis coveralls

script:
  - tox -e clean,build_test,codegen PRINT=1 PYTHON_CMD=python
  - tox

after_success:
  - travis_retry coveralls --rcfile=tools/coverage_unit_tests.rc

